fix build with musl > 1.2.5
musl removed basename declaration in string.h since version 1.2.5 and
https://github.com/bminor/musl/commit/725e17ed6dff4d0cd22487bb64470881e86a92e7
resulting in the following build failure:

/home/autobuild/autobuild/instance-3/output-1/build/rtty-8.1.0/src/file.c: In function 'start_upload_file':
/home/autobuild/autobuild/instance-3/output-1/build/rtty-8.1.0/src/file.c:156:24: error: implicit declaration of function 'basename' [-Werror=implicit-function-declaration]
  156 |     const char *name = basename(path);
      |                        ^~~~~~~~
/home/autobuild/autobuild/instance-3/output-1/build/rtty-8.1.0/src/file.c:156:24: error: initialization of 'const char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]

To fix this build failure, include libgen.h and make a copy of path
before passing it to GNU basename as it doesn't take a const parameter

Fixes:
 - http://autobuild.buildroot.org/results/411946f0ef49471a38a94dce4b7bea2609019f5d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>